service: projetoFinalGrupo2
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  httpApi:
    cors: true
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "lambda:InvokeFunction"
          - "lambda:PublishLayerVersion"
          - "rekognition:DetectText"
          - "lex:RunBot"
          - "lex:PostText"
          - "polly:SynthesizeSpeech"
          - "execute-api:*"
          - "s3:GetObject"
          - "s3:PutObject"
        Resource: "*"

resources:
  Resources:
    ImagensInput:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "sprint9-images-input-${AWS::AccountId}"

    TextsOutput:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "sprint9-detected-texts-${AWS::AccountId}"

    AudioOutput:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "sprint9-synthesized-audios-${AWS::AccountId}"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  transcribeAudioFunction:
    handler: handler.transcribeAudio
    events:
      - httpApi:
          path: /transcribeAudio
          method: post
  transcribeTextFunction:
    handler: handler.transcribeText
    events:
      - httpApi:
          path: /transcribeText
          method: post
  rekognitionFunction:
    handler: textRekognition.img2txt
    events:
      - httpApi:
          path: /textRekognition
          method: post